# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2606db4dc94f95b139f6fc19163f3ca71f2ae70b9059403b9ad3b2a5ff1ca0ba833951ce2208c6706c23e24575935d945427e7bc5f99b39f407f8e6173ae606e

test:
  secret_key_base: 9fa6aecfcb78d83a382a771926057c21acc703b06e651479142433b57b9cd409e0888c67ffd833e64e3eb3fad79be6f248c0d473babaa63d2bc089ade2de9ed8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
